version: '3.2'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "18000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - proxy
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.entrypoints=https"
        - "traefik.http.routers.portainer.rule=Host(`portainer.<ChangeMe>.com`)"
        - "traefik.http.routers.portainer.service=portainer"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.http.routers.portainer.tls.certresolver=mytlschallenge"

        - "traefik.http.routers.portainer_http.entrypoints=http"
        - "traefik.http.routers.portainer_http.rule=Host(`portainer.<ChangeMe>.com`)"
        - "traefik.http.routers.portainer_http.middlewares=traefik-redirectscheme"
        - "traefik.http.middlewares.traefik-redirectscheme.redirectscheme.scheme=https"

networks:
  proxy:
    external: true
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data: